### ISSUE TITLE
Issue with separate downloads and share directories

### ISSUE THREAD

**Issue by doobnet** [maksis/airdcpp-release-validator#2]
As the title says, I have separate downloads and share directories to avoid sharing things that are not complete. I had hoped that I could use this extension to automatically verify when a download is complete. But after installing this extension and downloading something, I got the following message in the events view:

```
The bundle <bundle> isn't in a shared folder, please add it in share manually
```

I'm not 100% sure that the above message is from the extension, but I believe so.

**Comment by maksis** [comment]
That shouldn't be related to any extension as it's a core message. The application is designed in a way that bundles are generally meant to be downloaded directly into share.

**Comment by doobnet** [comment]
> That shouldn't be related to any extension as it's a core message

Oh, you're right. I tried uninstalling the extension and I still get the message. I guess I didn't pay enough attention before.

> The application is designed in a way that bundles are generally meant to be downloaded directly into share

Is that the whole application or only this extension?

Is support for separate download and share directories something that can be added? I'm not even sure if the extension is working or not because the documentation is a bit lacking in describing what happens if a bundle passes or doesn't pass the validators.

**Comment by doobnet** [comment]
I did some debugging locally and it seems like the path of the finished bundled is located in the `target` member and not `path`, as the code here [1]. Not sure if that's because I'm using a separate download directory.

[1] https://github.com/maksis/airdcpp-release-validator/blob/master/src/ScanRunners.js#L58

**Comment by maksis** [comment]
> I did some debugging locally and it seems like the path of the finished bundled is located in the target member and not path

Ow, [that's correct](http://docs.airdcpp.apiary.io/#reference/queue/hooks/bundle-finished). I guess that I should also make the scanner throw on invalid paths (and possibly log the number of files/directories that were scanned for easier functionality check).

> Is support for separate download and share directories something that can be added?

Downloading bundles directly to the final destination in share is the way how the app has been optimized (intended) to be used, but naturally it will work even if you don't use it like that. You'll just get a reminder to add them in share manually. Items downloaded directly inside a shared directory will be shared without hashing as soon as they finish downloading and pass possible validations, which should help with spreading the faster.

> I'm not even sure if the extension is working or not because the documentation is a bit lacking in describing what happens if a bundle passes or doesn't pass the validators.

Yeah, that could added in the docs.

**Comment by maksis** [comment]
This issue has been fixed in version 0.2.0. I've also improved the README.

**Comment by doobnet** [comment]
Thanks. So, if a bundle passes all validations, not notification or similar is shown?

**Comment by maksis** [comment]
Currently no. Scanned bundles are logged in `Settings\extensions\airdcpp-release-validator\logs` though.
