### ISSUE TITLE
Local installation

### ISSUE THREAD

**Issue by doobnet** [maksis/airdcpp-release-validator#3]
I've done some modifications to this extension locally that I don't won't to make publicly available (or at least or not ready yet). I've tried running the extension using `npm run build` and `npm start`, which works fine. The extension is registered and shows up in the client.

How can I install the extension so I can manage (start and stop) it from within the client without publishing to the npm repository? Is it enough to copy some files to the extension folder in the client config directory? In that case, which files do I need and is it enough to compile using `npm run build`?

I'm completely new to Node and npm.

**Comment by maksis** [comment]
Yeah, running `npm run build` and copying the bundled files from dist will be enough

**Comment by doobnet** [comment]
Yes, that worked, thanks.
