### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by doobnet** [maksis/airdcpp-release-validator#6]
This extension has been working fine for quite a while. But now suddenly it won't start. In the error log I get this message: `Failed to connect to server [::1]:5600/api/v1/, exiting..`.

I'm running AirDC++w 2.6.0 x86_64.

**Comment by maksis** [comment]
The extension works fine for me with version 2.6.0.

Which version of the extension are you using? Are you able to run other extensions? Which version of node.js do you have installed?

**Comment by doobnet** [comment]
> Which version of the extension are you using?

0.2.2.

> Are you able to run other extensions?

No. I've tried airdcpp-message-emailer and airdcpp-runscript-extension.

> Which version of node.js do you have installed?

I have 8.12.0. I tried with 10.15.3 as well (current LTS), didn't make any difference.

I'm running this on a Qnap NAS, running Linux x86_64.

**Comment by maksis** [comment]
Are you able to test sending requests (e.g. wget/curl/opening it with a browser) to the URL http://[::1]:5600/api/v1/ from the same server?

**Comment by doobnet** [comment]
Yeah, I get `Couldn't connect to server`. It works with `localhost` instead of `[::1]` so I'm guessing it's something related to IPv6.

This issue occurred before I update to `2.6.0` and `0.2.2`. Then I tried to update both airdc and the extension and still got the same issue. I haven't touched airdc before this issue occurred so I'm starting to think something has changed in the system. I have update the system once or twice. Not sure what I should look for. Since everything else seems to be working on the system I'm guessing the other parts are not using IPv6 or that either Node.js or something in airdc or the extension fails.

Is it possible to configure to use IPv4 instead, as a workaround?

**Comment by maksis** [comment]
You can change the HTTP bind address from the web server settings. The application shouldn't use an IPv6 address if IPv6 is not supported on by the system though.

**Comment by doobnet** [comment]
> The application shouldn't use an IPv6 address if IPv6 is not supported on by the system though.

I get this in the event log:

```
Connectivity (IPv6): IPv6 connectivity has been disabled as no public IPv6 address was detected
Connectivity (IPv4): Local network with possible NAT detected, trying to map the ports...
```

**Comment by maksis** [comment]
Public IPv6 is not needed for running extensions. Are there inet6 addresses available if you check `ifconfig`?

**Comment by doobnet** [comment]
> Are there inet6 addresses available if you check ifconfig?

It is for `eth0` but not for `lo`. Not sure if that's expected.

**Comment by maksis** [comment]
So you only have a public IPv6 address but not a local one (::1)? The application may not handle such cases correctly.

**Comment by doobnet** [comment]
That might be the case. I've configured a bind address, the extensions are starting now. Thanks.

**Comment by maksis** [comment]
Moved to https://github.com/airdcpp-web/airdcpp-webclient/issues/321
