### ISSUE TITLE
Issue with false SFV positive matching MP3 regex

### ISSUE THREAD

**Issue by doobnet** [maksis/airdcpp-release-validator#8]
If a bundle contains a directory with a file and its name have a pattern like: `foobar.0701.mkv`, the extension incorrectly recognizes this as an SFV directory based on the regular expression for identifying MP3 files. Example:

```
.
├── Sample
│   └── foobar.0701.mkv
└── foobar.0701.sfv
```

The extension will incorrectly recognize the `foobar.0701.mkv` file as an MP3 file, based on the regular expression. Therefore it will assume that the `Sample` directory should have a SFV file, which it doesn't and therefore the validation will not pass.

**Comment by maksis** [comment]
Yeah, seems like all regexes need to be modified to only match the full string (which is how they behaved with `regex_match` in C++)

**Comment by maksis** [comment]
These are fixed in version 0.3.0
